import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import ProductItem from "../components/product/ProductItem";

export interface Product {
  key?: string;
  id: string;
  category: string;
  description: string;
  image: string;
  price: string;
  rating: Array<any>;
  title: string;
}
export const getStaticProps: GetStaticProps = async ({response}: any) => {
  console.log(response)
  const res = await fetch("https://fakestoreapi.com/products");
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
};

const Home: NextPage = (props: any) => {
  const [products, setProducts] = useState(props.data);

  const RenderProduct = () => {
    return products.length === 0 ? (
      <h2>No Products</h2>
    ) : (
      products
        .slice(0, 10)
        .map((item: Product) => <ProductItem key={item.id} product={item} />)
    );
  };

  return (
    <div className="products">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RenderProduct />
    </div>
  );
};

export default Home;
